# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue-essencial
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:

  # 1. Fonts Office
  - type: files
    files:
      - source: office_fontes
        destination: /usr/share/fonts/office_fontes

  # 2. RPM packages
  - type: dnf
    install:
      packages:
        - distrobox
        - fish
                
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # 3. Scripts
  - type: script
    scripts:
      - install-hatter-icons.sh
      - configure-gnome.sh
      - add-flathub.sh
      - remove-fedora-flatpaks.sh
      - install-rom.sh
      - disable-network-wait.sh

  # 4. Install Flathub Flatpaks
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.mattjakeman.ExtensionManager
          - com.brave.Browser
          - com.github.neithern.g4music
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.Contacts
          - org.fedoraproject.MediaWriter
          - org.gnome.font-viewer
          - org.gnome.FileRoller
          - org.gnome.Loupe
          - org.gnome.Papers
          - org.gnome.SimpleScan
          - org.gnome.Snapshot
          - org.gnome.Showtime
          - org.gnome.TextEditor
          - org.onlyoffice.desktopeditors
          - it.mijorus.smile
          - io.github.flattool.Ignition
          - io.github.thetumultuousunicornofdarkness.cpu-x
          - io.missioncenter.MissionCenter
          - org.localsend.localsend_app
          - page.tesk.Refine
          - page.codeberg.libre_menu_editor.LibreMenuEditor
          - org.gtk.Gtk3theme.adw-gtk3 
          - org.gtk.Gtk3theme.adw-gtk3-dark
          
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
